CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID     NUMBER(6)       PRIMARY KEY,
  FIRST_NAME      VARCHAR2(50)    NOT NULL,
  LAST_NAME       VARCHAR2(50)    NOT NULL,
  EMAIL           VARCHAR2(100)   NOT NULL,
  PHONE_NUMBER    VARCHAR2(20),
  HIRE_DATE       DATE            NOT NULL,
  JOB_TITLE       VARCHAR2(60),
  DEPARTMENT      VARCHAR2(60),
  SALARY          NUMBER(9,2),
  MANAGER_ID      NUMBER(6),
  PLANT_LOCATION  VARCHAR2(60),
  CONSTRAINT FK_EMPLOYEES_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1001, 'Karen', 'Whitfield', 'karen.whitfield@acmemfg.com', '316-555-0110', TO_DATE('2014-03-10','YYYY-MM-DD'), 'Plant Manager', 'Operations', 142000, NULL, 'Wichita KS');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1002, 'Marcus', 'Nolan', 'marcus.nolan@acmemfg.com', '316-555-0111', TO_DATE('2015-06-22','YYYY-MM-DD'), 'Production Supervisor', 'Production', 98000, 1001, 'Wichita KS');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1003, 'Priya', 'Ramanathan', 'priya.ramanathan@acmemfg.com', '316-555-0112', TO_DATE('2016-01-15','YYYY-MM-DD'), 'Quality Engineer', 'Quality Assurance', 91000, 1001, 'Wichita KS');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1004, 'Diego', 'Salinas', 'diego.salinas@acmemfg.com', '614-555-0113', TO_DATE('2017-09-05','YYYY-MM-DD'), 'Supply Chain Analyst', 'Supply Chain', 84000, 1001, 'Columbus OH');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1005, 'Hannah', 'Ostrowski', 'hannah.ostrowski@acmemfg.com', '614-555-0114', TO_DATE('2018-04-18','YYYY-MM-DD'), 'Systems Engineer', 'Engineering', 105000, 1001, 'Columbus OH');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1006, 'Terrence', 'Baptiste', 'terrence.baptiste@acmemfg.com', '864-555-0115', TO_DATE('2013-11-02','YYYY-MM-DD'), 'Maintenance Technician', 'Maintenance', 72000, 1002, 'Greenville SC');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1007, 'Yuki', 'Tanaka', 'yuki.tanaka@acmemfg.com', '864-555-0116', TO_DATE('2019-07-29','YYYY-MM-DD'), 'Assembly Technician', 'Production', 68000, 1002, 'Greenville SC');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1008, 'Omar', 'Farouk', 'omar.farouk@acmemfg.com', '303-555-0117', TO_DATE('2020-02-11','YYYY-MM-DD'), 'Quality Inspector', 'Quality Assurance', 65000, 1003, 'Denver CO');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1009, 'Grace', 'Odom', 'grace.odom@acmemfg.com', '303-555-0118', TO_DATE('2012-08-14','YYYY-MM-DD'), 'Procurement Specialist', 'Supply Chain', 79000, 1004, 'Denver CO');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1010, 'Felix', 'Marchetti', 'felix.marchetti@acmemfg.com', '615-555-0119', TO_DATE('2021-05-03','YYYY-MM-DD'), 'Data Engineer', 'Engineering', 110000, 1005, 'Nashville TN');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1011, 'Aisha', 'Bello', 'aisha.bello@acmemfg.com', '615-555-0120', TO_DATE('2016-10-27','YYYY-MM-DD'), 'IT Support Specialist', 'IT', 71000, 1005, 'Nashville TN');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1012, 'Connor', 'Fitzgerald', 'connor.fitzgerald@acmemfg.com', '214-555-0121', TO_DATE('2015-12-09','YYYY-MM-DD'), 'Financial Analyst', 'Finance', 88000, 1001, 'Dallas TX');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1013, 'Meera', 'Iyer', 'meera.iyer@acmemfg.com', '214-555-0122', TO_DATE('2022-03-21','YYYY-MM-DD'), 'HR Business Partner', 'HR', 86000, 1001, 'Dallas TX');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1014, 'Bradley', 'Nunes', 'bradley.nunes@acmemfg.com', '316-555-0123', TO_DATE('2011-01-30','YYYY-MM-DD'), 'Senior Production Supervisor', 'Production', 102000, 1001, 'Wichita KS');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1015, 'Sofia', 'Delgado', 'sofia.delgado@acmemfg.com', '316-555-0124', TO_DATE('2023-06-12','YYYY-MM-DD'), 'Assembly Technician', 'Production', 64000, 1014, 'Wichita KS');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1016, 'Nathaniel', 'Growe', 'nathaniel.growe@acmemfg.com', '614-555-0125', TO_DATE('2017-02-08','YYYY-MM-DD'), 'Quality Engineer', 'Quality Assurance', 93000, 1003, 'Columbus OH');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1017, 'Wenqing', 'Zhou', 'wenqing.zhou@acmemfg.com', '864-555-0126', TO_DATE('2020-09-17','YYYY-MM-DD'), 'Systems Engineer', 'Engineering', 107000, 1005, 'Greenville SC');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1018, 'Latasha', 'Freeman', 'latasha.freeman@acmemfg.com', '303-555-0127', TO_DATE('2019-04-25','YYYY-MM-DD'), 'Maintenance Technician', 'Maintenance', 74000, 1006, 'Denver CO');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1019, 'Ravi', 'Chandrasekaran', 'ravi.chandrasekaran@acmemfg.com', '615-555-0128', TO_DATE('2014-08-19','YYYY-MM-DD'), 'Procurement Specialist', 'Supply Chain', 81000, 1009, 'Nashville TN');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_TITLE, DEPARTMENT, SALARY, MANAGER_ID, PLANT_LOCATION) VALUES (1020, 'Emily', 'Sawyer', 'emily.sawyer@acmemfg.com', '214-555-0129', TO_DATE('2021-11-30','YYYY-MM-DD'), 'IT Support Specialist', 'IT', 73000, 1011, 'Dallas TX');

COMMIT;
